### PR TITLE
Create inference_single_cvimage.py to inference on the single image.

### PR DESCRIPTION
**Pull request by ausk**
A single file with a simple class FCOS, mainly to inference the single opencv image without much depencency with maskrcnn_benchmark. Here is the result.

创建一个简单的类 FCOS，用于对单张图像进行推理，减少对 maskrcnn_benchmark 的依赖, 下图即是推理结果。

image

### CODE REVIEW

**Comment by ausk** [comment]
如果是对单张图像进行测试，那么使用 inferenc_single_cvimage.py 文件即可（注意修改图片名称、  配置文件和模型文件路径。）

如果对数据集进行测试，则修改 `paths_catalog.py` 文件里的 路径 DATA_DIR： `maskrcnn_benchmark\config\paths_catalog.py`

下面是对 Coco2017 val 测试：
(1) Win10 + Pytorch 1.0.1 能跑，Win10 + Pytorch 1.0.1 + FCOS_R_50_FPN_1x.pth + Coco2017val, 只测试前 100 张 (心疼我的超薄本)：
```
...
2019-04-15 22:02:06,395 maskrcnn_benchmark INFO:
PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 10 家庭中文版
GCC version: (i686-posix-sjlj, built by strawberryperl.com project) 4.9.2
CMake version: version 3.13.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
D:\Programs\Nvidia\CudaToolkit\v10.1\bin\cudnn64_7.dll
...

Evaluate annotation type *bbox*
DONE (t=7.13s).
Accumulating evaluation results...
DONE (t=1.78s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.014
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.006
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.014
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.006
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.009
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.009
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.014
2019-04-15 22:03:28,963 maskrcnn_benchmark.inference INFO: OrderedDict([('bbox', OrderedDict([('AP', 0.010632005300624909), ('AP50', 0.01441064410190619), ('AP75', 0.011626370622375929), ('APs', 0.005708384806576942), ('APm', 0.009459472732874858), ('APl', 0.013959432553801273)]))])
```

(2) Ubuntu 16.04 + Cuda10 + pytorch1.0.1.post2 + Coco2017val （服务器上测试）
```
...
Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN V
...

Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.0.1.post2              pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi

...

2019-04-15 22:23:00,895 maskrcnn_benchmark.inference INFO: Start evaluation on coco_2017_val dataset(5000 images).
100%|████████████████████████████████████████| 1251/1251 [07:14<00:00,  4.09it/s]
2019-04-15 22:30:15,214 maskrcnn_benchmark.inference INFO: Total run time: 0:07:14.317999 (0.08686359972953796 s / img per device, on 1 devices)
2019-04-15 22:30:15,215 maskrcnn_benchmark.inference INFO: Model inference time: 0:06:16.214950 (0.07524299001693725 s / img per device, on 1 devices)
2019-04-15 22:30:15,836 maskrcnn_benchmark.inference INFO: Preparing results for COCO format
2019-04-15 22:30:15,836 maskrcnn_benchmark.inference INFO: Preparing bbox results
2019-04-15 22:30:18,150 maskrcnn_benchmark.inference INFO: Evaluating predictions
Loading and preparing results...
DONE (t=4.93s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=80.12s).
Accumulating evaluation results...
DONE (t=18.35s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.366
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.561
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.389
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.208
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.403
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.473
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.316
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.502
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.525
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.332
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.572
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.673
2019-04-15 22:32:13,378 maskrcnn_benchmark.inference INFO: OrderedDict([('bbox', OrderedDict([('AP', 0.36598954684743584), ('AP50', 0.5607506103634963), ('AP75', 0.38890046536382367), ('APs', 0.20841979113320555), ('APm', 0.4033713593033273), ('APl', 0.4727926975514393)]))])
```

**Comment by tianzhi0549** [comment]
@ausk Thank you for your pull request. We have two suggestions for it.
1) Can you remove all Chinese comments in your code since the code with Chinese characters might encounter encoding errors on some environments? Also, It would be very helpful if you can translate your comments on GitHub to English. It can help people who don't understand Chinese to use your code.
2) Can you pass all parameters of the script such as `fpath`, `config_file` and `weight` by command line parameters with `argparse`? It will make the script easier to use.

Once you finish the above suggestions, we can merge your pull request. Thank you!

**Comment by ausk** [comment]
@tianzhi0549  Remove the Chinese comments in the code, and mofify to use argparse. It works on my PC, but maybe you still should test before merge it.

**Comment by tianzhi0549** [comment]
@ausk OK. Thank you very much! Let's merge it.

**Comment by wadesunyang** [comment]
I have a question, why the scores are so low?     for example, i trained the coco2017 with the code, and the score is always low, so i couldn't set the threshold ，such as the bike is 0.248 in your picture, in my test, the people's score maybe 0.2-0.4 sometimes, when i set the threshold to 0.2, some false positive occur。   
could you tell me how to solve the problem?

**Comment by xs020420** [comment]
Hi！When I use this code for detecting, it presents a densy result. I notice that there is no NMS post-processing in this code . Is it right?

**Comment by tianzhi0549** [comment]
@xs020420 Please use https://github.com/tianzhi0549/FCOS/blob/master/demo/fcos_demo.py instead.

**Comment by xs020420** [comment]
> @xs020420 Please use https://github.com/tianzhi0549/FCOS/blob/master/demo/fcos_demo.py instead.

Thanks for suggestion. Maybe I should read the overall code carefully before modification.

**Pull request merged**
